### PR TITLE
organization and cleaning of several functions

### LINKED ISSUE #480: Clean currently not used functions
I execute a profile with octave running `runTestProblems_local.m` and the functions that are no used are:

- [x] Actualización.m
- [x] aeroForce.m
- [ ] analyticSolVerif
- [ ] computeNormalForces
- [ ] createRectangular
- [ ] createSolidRegularMesh
- [ ] DerivFun
- [ ] linearBucklingAnalysisPlots
- [ ] loadsAngleSpring
- [ ] massMatAssembly
- [ ] MatrizMasaCompleja
- [ ] modelExtract
- [ ] stabilityAnalysis
- [ ] structsToCellsConv
- [ ] tablesFunc
- [ ] tangentInertialMassMatrix

Maybe we could define a header for each function and define a uniform nomenclature for naming functions :100:

### PR DESCRIPTION
**Pull request by mvanzulli**
This PR closes #480

### CODE REVIEW

**Comment by jorgepz** [comment]
As we just discussed, I agree that DXF files are not in our current focus/scope, then I agree to remove those functions. I suggest you also moving S. Toro from author of code to contributor of ONSAS (as former author of code).

**Comment by jorgepz** [comment]
Thanks. Let me know when the pr is ready for review...

**Comment by mvanzulli** [comment]
> Thanks. Let me know when the pr is ready for review...

Now it is, check the new tree of folders.

**Review by jorgepz — CHANGES_REQUESTED** [review]
estoy armando PR con cambios propuestos... de todas formas el orden de los autores no coincide con el del citation.aff

**Comment by jorgepz** [comment]
i already updated the citation file in https://github.com/ONSAS/ONSAS.m/pull/485 ...

**Comment by mvanzulli** [comment]
> i already updated the citation file in #485 ... i'll try to fix the conflict...

Sorry I misunderstood, I can also delete the last commit of this branch by using:

```bash
git reset --hard HEAD~1
git push --force
```

**Comment by jorgepz** [comment]
no worries it is fixed... i think // no hay problema

**Review by jorgepz — APPROVED** [review]

**Pull request merged**
