### PR TITLE
computeFext_allMethods

### LINKED ISSUE #662: Add current solution information as input in the userloadfunction for Newmark Method
update the newmark method to add the current solution information as input to the userloadfunction

### PR DESCRIPTION
**Pull request by santiago-correa-89**
This PR resolve #662

### CODE REVIEW

**Comment by santiago-correa-89** [comment]
This PR "Resolve" #662

**Review by jorgepz — CHANGES_REQUESTED** [review]
thanks for the contribution santiago. i suggest you to update your branch. also for the arc length and newton raphson methods you should not pass the velocities and accellerations as arguments since those methods are for static analyses. moreover, the output/script changes should not be added, please remove them from your branch. we can go on with the discussion vía slack

**Review by santiago-correa-89 — COMMENTED** [review]
Edited the file system_assembler and removed report files

**Review by jorgepz — APPROVED** [review]

**Comment by jorgepz** [comment]
You can merge @santiago-correa-89

**Pull request merged**
